if __name__ == "__main__":
    from crazy_duck import CrazyDuck
    duck1 = CrazyDuck()
    duck2 = CrazyDuck("Chino")
    duck3 = CrazyDuck("Howard")
    duck1.add_cuack("Drinking")
    duck1.add_cuack("Gambling")
    duck1.add_cuack([1, 2, 3, 4, 5, 6])
    duck2.add_cuack("Drinking")
    duck2.add_cuack("Bad football teams")
    duck3.add_cuack("Drinking")
    duck3.add_cuack("Rock music")
    duck3.add_cuack([1, 2, 3, 4, 5, 6])
    print(str(duck1))
    print(str(duck2))
    print(str(duck3))
    print(duck1["name"])
    print(duck1["cuacks"])
    print(duck1["my first cuack"])
    print(duck1[0])
    print(duck1[1])
    print(duck1[2])
    print(duck1[-1])
    print(duck1 == duck2)
    print(duck1 == duck3)
    print(duck1 == duck1)